services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  postgraphile:
    image: graphile/postgraphile:4
    ports:
      - 5000:5000
    command: '--connection postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB} --schema public --watch'
    depends_on:
      - postgres
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:5050
    env_file:
      - postgres/pgadmin.env
    depends_on:
      - postgres
    volumes:
      - ./postgres/servers.json:/pgadmin4/servers.json

  sqlite:
    build: ./sqlite
    volumes:
      - ./sqlite/data:/db
    working_dir: /db
    command: sqlite3 /db/students.db "select 1"
    
  adminer:
    build: ./sqlite/adminer
    volumes:
      - ./sqlite/data:/db
    ports:
      - 8080:8080
    depends_on:
      - sqlite

  tuql:
    build: ./sqlite/tuql
    volumes:
      - ./sqlite/data:/db
    working_dir: /app
    command: npx tuql --db /db/students.db --port 8888 --graphiql
    ports:
      - 8888:8888
    depends_on:
      - sqlite

volumes:
  postgres_data:
