services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file: .env
    ports:
      - 1401:1433
    volumes:
      - mssql_data:/var/opt/mssql

  postgres:
    image: postgres:14-alpine
    env_file: .env
    restart: unless-stopped
    volumes:
    - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer:4
    ports:
      - 8081:8080
    depends_on:
      - mssql
      - postgres

  hasura:
    image: hasura/graphql-engine:v2.2.0
    env_file: .env
    ports:
      - 8090:8080
    depends_on:
      - mssql
      - postgres
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

volumes:
  mssql_data:
  postgres_data:
    